//Matríz de conetenido
// 1 => estarán visibles
// 0 => el estudiante deberá escribirlo
function matrixAcelerando(){
	return [
		{"matrix":[65, 37, 28, 23, 14, 14, 13, 10, 4, 10, 6, 7, 3, 1, 9], "inputs":[1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0], },
		{"matrix":[48, 20, 28, 8, 12, 16, 3, 5, 7, 9, 1, 2, 3, 4, 5], "inputs":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], },
		{"matrix":[96, 40, 56, 16, 24, 32, 6, 10, 14, 18, 2, 4, 6, 8, 10], "inputs":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], },
		{"matrix":[30, 15, 15, 8, 7, 8, 4, 4, 3, 5, 2, 2, 2, 1, 4], "inputs":[0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0], },
		{"matrix":[32, 16, 16, 8, 8, 8, 4, 4, 4, 4, 2, 2, 2, 2, 2], "inputs":[1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1], },
		{"matrix":[71, 38, 33, 19, 19, 14, 10, 9, 10, 4, 8, 2, 7, 3, 1], "inputs":[0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1], },
		{"matrix":[96, 56, 40, 32, 24, 16, 18, 14, 10, 6, 10, 8, 6, 4, 2], "inputs":[0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },

		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },

		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
	];
}


/* Medio
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },

		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },

		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
*/

/* Avanzado
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },

		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },

		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
		{"matrix":[], "inputs":[], },
*/